# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(443, 371)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setText("")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.verticalLayout_4.addWidget(self.name)
        self.second_name = QtWidgets.QLineEdit(self.centralwidget)
        self.second_name.setText("")
        self.second_name.setAlignment(QtCore.Qt.AlignCenter)
        self.second_name.setObjectName("second_name")
        self.verticalLayout_4.addWidget(self.second_name)
        self.surname = QtWidgets.QLineEdit(self.centralwidget)
        self.surname.setText("")
        self.surname.setAlignment(QtCore.Qt.AlignCenter)
        self.surname.setObjectName("surname")
        self.verticalLayout_4.addWidget(self.surname)
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setText("")
        self.login.setAlignment(QtCore.Qt.AlignCenter)
        self.login.setObjectName("login")
        self.verticalLayout_4.addWidget(self.login)
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setText("")
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.verticalLayout_4.addWidget(self.password)
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setText("")
        self.email.setAlignment(QtCore.Qt.AlignCenter)
        self.email.setObjectName("email")
        self.verticalLayout_4.addWidget(self.email)
        self.phone_number = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_number.setText("")
        self.phone_number.setAlignment(QtCore.Qt.AlignCenter)
        self.phone_number.setObjectName("phone_number")
        self.verticalLayout_4.addWidget(self.phone_number)
        self.city = QtWidgets.QLineEdit(self.centralwidget)
        self.city.setText("")
        self.city.setAlignment(QtCore.Qt.AlignCenter)
        self.city.setObjectName("city")
        self.verticalLayout_4.addWidget(self.city)
        self.school = QtWidgets.QLineEdit(self.centralwidget)
        self.school.setText("")
        self.school.setAlignment(QtCore.Qt.AlignCenter)
        self.school.setObjectName("school")
        self.verticalLayout_4.addWidget(self.school)
        self.form = QtWidgets.QLineEdit(self.centralwidget)
        self.form.setText("")
        self.form.setAlignment(QtCore.Qt.AlignCenter)
        self.form.setObjectName("form")
        self.verticalLayout_4.addWidget(self.form)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.registrate = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.registrate.setFont(font)
        self.registrate.setObjectName("registrate")
        self.horizontalLayout_2.addWidget(self.registrate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setPlaceholderText(_translate("MainWindow", "ИМЯ*"))
        self.second_name.setPlaceholderText(_translate("MainWindow", "ОТЧЕСТВО"))
        self.surname.setPlaceholderText(_translate("MainWindow", "ФАМИЛИЯ*"))
        self.login.setPlaceholderText(_translate("MainWindow", "ЛОГИН*"))
        self.password.setPlaceholderText(_translate("MainWindow", "ПАРОЛЬ*"))
        self.email.setPlaceholderText(_translate("MainWindow", "ПОЧТА*"))
        self.phone_number.setPlaceholderText(_translate("MainWindow", "НОМЕР ТЕЛЕФОНА"))
        self.city.setPlaceholderText(_translate("MainWindow", "ГОРОД"))
        self.school.setPlaceholderText(_translate("MainWindow", "ШКОЛА"))
        self.form.setPlaceholderText(_translate("MainWindow", "КЛАСС"))
        self.registrate.setText(_translate("MainWindow", "ЗАРЕГИСТРИРОВАТЬСЯ"))

